# Generated by Django 5.2.6 on 2025-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('age', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('is_admin', models.BooleanField()),
                ('is_teacher', models.BooleanField()),
                ('is_student', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
