# Generated by Django 5.2.6 on 2025-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_group_student_group_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
