# Generated by Django 5.2.6 on 2025-09-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lesson_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='students',
            new_name='students_set',
        ),
    ]
