# Generated by Django 5.2.6 on 2025-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_students_group_students_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='status',
        ),
        migrations.AddField(
            model_name='attendence',
            name='absent_students',
            field=models.ManyToManyField(blank=True, related_name='absents', to='app.student'),
        ),
    ]
