# Generated by Django 5.2.6 on 2025-09-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_attendence_status_attendence_absent_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='students',
        ),
    ]
