# Generated by Django 5.2.6 on 2025-10-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_group_id_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group',
        ),
    ]
