# Generated by Django 5.2.6 on 2025-10-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_group_id_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
