# Generated by Django 5.2.6 on 2025-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='floor',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='started_day',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='lesson',
            name='days_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
