# Generated by Django 5.2.6 on 2025-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='days_week',
        ),
        migrations.AddField(
            model_name='homework',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='mark',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
