# Generated by Django 5.2.6 on 2025-10-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_lesson_days_week_homework_is_checked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='file',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='app.homework'),
        ),
        migrations.CreateModel(
            name='HomeworkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='student_homework_file/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='student_homework_photo/')),
                ('text', models.TextField(blank=True, null=True)),
                ('mark', models.SmallIntegerField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='app.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_upload', to='app.student')),
            ],
        ),
    ]
