# Generated by Django 5.2.6 on 2025-10-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_uploaded_at_homework_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='title',
        ),
    ]
