# Generated by Django 5.2.7 on 2025-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_ed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_ed',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, default='static/videos/default.mp4', null=True, upload_to='uploads/videos/'),
        ),
    ]
