# Generated by Django 5.2.7 on 2025-10-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_created_ed_user_updated_ed_alter_lesson_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_ed',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_ed',
            new_name='updated_at',
        ),
    ]
