# Generated by Django 5.2.7 on 2025-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_created_ed_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
