# Generated by Django 5.2.7 on 2025-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_student_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
